version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: steeze_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: steeze123
      POSTGRES_DB: steeze
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
